name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version:

      - name: Build
        run: npm run build

      - name: Deploy
        if: success() # Only runs if the previous step (Build) was successful
        run: npm run deploy
